version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    container_name: kube-mysql-uat
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "$MYSQL_PORT:3306"
    volumes:
      - $MYSQL_VOL_PATH:/var/lib/mysql
